<?php

/**
 * Legacy upload folder/prefix semantics from legacy.selloff/app/Models/UploadModel.php
 *
 * Paths resolve to uploads/{folder}/[{Ym}/]{prefix}{token}.{ext}
 * Product DB rows store the relative segment after uploads/images/ (e.g. 202604/img_w960_….webp).
 */
return [
    'image_format' => env('SELLOFF_IMAGE_FILE_FORMAT', 'WEBP'), // Fallback when platform_settings.image_file_format is unset

    'product_sizes' => [
        'small' => 480,
        'default' => 960,
        'big' => 1600,
    ],

    // Fallbacks when platform_settings watermark keys are unset
    'watermark' => [
        'product_enabled' => env('SELLOFF_WATERMARK_PRODUCT', false),
        'blog_enabled' => env('SELLOFF_WATERMARK_BLOG', false),
        'thumbnail_enabled' => env('SELLOFF_WATERMARK_THUMBNAIL', false),
        'text' => env('SELLOFF_WATERMARK_TEXT', ''),
        'font_path' => env('SELLOFF_WATERMARK_FONT', base_path('resources/fonts/OpenSans-Bold.ttf')),
        'font_size' => (float) env('SELLOFF_WATERMARK_FONT_SIZE', 28),
        'horizontal' => env('SELLOFF_WATERMARK_ALIGN_H', 'right'),
        'vertical' => env('SELLOFF_WATERMARK_ALIGN_V', 'bottom'),
    ],

    'contexts' => [
        'temp' => [
            'kind' => 'direct',
            'folder' => 'temp',
            'prefix' => 'temp_',
            'date_folder' => false,
            'extensions' => ['jpg', 'jpeg', 'webp', 'png', 'gif', 'mp4', 'mp3', 'pdf'],
            'max_kb' => 10240,
        ],
        'product' => [
            'kind' => 'product_variants',
            'folder' => 'images',
            'date_folder' => true,
            'watermark' => 'product',
            'quality' => 85,
            'extensions' => ['jpg', 'jpeg', 'webp', 'png', 'gif'],
            'max_kb' => 10240,
        ],
        'profile' => [
            'kind' => 'optimized',
            'folder' => 'profile',
            'date_folder' => true,
            'quality' => 100,
            'extensions' => ['jpg', 'jpeg', 'webp', 'png', 'gif'],
            'variants' => [
                'default' => ['prefix' => 'profile_', 'method' => 'cover', 'width' => 300, 'height' => 300],
                'cover' => ['prefix' => 'cover_', 'method' => 'cover', 'width' => 1920, 'height' => 400],
            ],
            'default_variant' => 'default',
        ],
        'blog' => [
            'kind' => 'optimized',
            'folder' => 'blog',
            'date_folder' => true,
            'watermark' => 'blog',
            'quality' => 85,
            'extensions' => ['jpg', 'jpeg', 'webp', 'png', 'gif'],
            'variants' => [
                'small' => ['prefix' => 'img_', 'method' => 'cover', 'width' => 500, 'height' => 332],
                'large' => ['prefix' => 'img_', 'method' => 'resize', 'width' => 1280, 'height' => null],
            ],
            'default_variant' => 'large',
        ],
        'category' => [
            'kind' => 'optimized',
            'folder' => 'category',
            'date_folder' => true,
            'prefix' => 'category_',
            'method' => 'cover',
            'width' => 420,
            'height' => 420,
            'quality' => 85,
            'extensions' => ['jpg', 'jpeg', 'webp', 'png', 'gif'],
        ],
        'slider' => [
            'kind' => 'optimized',
            'folder' => 'slider',
            'date_folder' => true,
            'quality' => 85,
            'extensions' => ['jpg', 'jpeg', 'webp', 'png', 'gif'],
            'variants' => [
                'mobile' => ['prefix' => 'slider_', 'method' => 'cover', 'width' => 768, 'height' => 500],
                'desktop' => ['prefix' => 'slider_', 'method' => 'cover', 'width' => 1920, 'height' => 600],
            ],
            'default_variant' => 'desktop',
        ],
        'newsletter' => [
            'kind' => 'optimized',
            'folder' => 'blocks',
            'prefix' => 'newsletter_',
            'method' => 'cover',
            'width' => 500,
            'height' => 500,
            'date_folder' => true,
            'quality' => 100,
            'extensions' => ['jpg', 'jpeg', 'webp', 'png', 'gif'],
        ],
        'affiliate' => [
            'kind' => 'optimized',
            'folder' => 'blocks',
            'prefix' => 'img_',
            'method' => 'cover',
            'width' => 1200,
            'height' => 980,
            'date_folder' => true,
            'quality' => 85,
            'extensions' => ['jpg', 'jpeg', 'webp', 'png', 'gif'],
        ],
        'brand' => [
            'kind' => 'optimized',
            'folder' => 'blocks',
            'prefix' => 'brand_',
            'method' => 'resize',
            'width' => 256,
            'height' => null,
            'date_folder' => true,
            'quality' => 100,
            'extensions' => ['jpg', 'jpeg', 'webp', 'png', 'gif'],
        ],
        'flag' => [
            'kind' => 'optimized',
            'folder' => 'blocks',
            'prefix' => 'flag_',
            'method' => 'resize',
            'width' => null,
            'height' => 100,
            'date_folder' => true,
            'quality' => 100,
            'extensions' => ['jpg', 'jpeg', 'webp', 'png', 'gif'],
        ],
        'logo' => [
            'kind' => 'direct',
            'folder' => 'logo',
            'prefix' => 'logo_',
            'date_folder' => false,
            'extensions' => ['jpg', 'jpeg', 'png', 'gif', 'svg', 'webp'],
            'max_kb' => 5120,
        ],
        'favicon' => [
            'kind' => 'direct',
            'folder' => 'logo',
            'prefix' => 'favicon_',
            'date_folder' => false,
            'extensions' => ['jpg', 'jpeg', 'png', 'gif', 'ico', 'webp'],
            'max_kb' => 2048,
        ],
        'pwa_logo' => [
            'kind' => 'pwa_logos',
            'folder' => 'logo',
            'date_folder' => false,
            'extensions' => ['jpg', 'jpeg', 'webp', 'png', 'gif'],
            'max_kb' => 5120,
        ],
        'ad' => [
            'kind' => 'direct',
            'folder' => 'blocks',
            'prefix' => 'block_',
            'date_folder' => true,
            'extensions' => ['jpg', 'jpeg', 'webp', 'png', 'gif'],
            'max_kb' => 10240,
        ],
        'receipt' => [
            'kind' => 'direct',
            'folder' => 'receipts',
            'prefix' => 'receipt_',
            'date_folder' => true,
            'extensions' => ['pdf', 'jpg', 'jpeg', 'png', 'webp', 'doc', 'docx', 'xls', 'xlsx'],
            'max_kb' => 10240,
        ],
        'video' => [
            'kind' => 'direct',
            'folder' => 'videos',
            'prefix' => 'video_',
            'date_folder' => true,
            'extensions' => ['mp4', 'webm'],
            'max_kb' => 51200,
        ],
        'audio' => [
            'kind' => 'direct',
            'folder' => 'audios',
            'prefix' => 'audio_',
            'date_folder' => true,
            'extensions' => ['mp3', 'wav'],
            'max_kb' => 20480,
        ],
        'digital_file' => [
            'kind' => 'direct',
            'folder' => 'digital-files',
            'prefix' => 'digital-file-',
            'date_folder' => false,
            'extensions' => ['zip', 'pdf', 'mp3', 'mp4', 'epub', 'jpg', 'jpeg', 'png'],
            'max_kb' => 51200,
        ],
        'attachment' => [
            'kind' => 'direct',
            'folder' => 'support',
            'prefix' => 'attachment_',
            'date_folder' => true,
            'extensions' => ['jpg', 'jpeg', 'png', 'gif', 'webp', 'pdf', 'doc', 'docx', 'txt', 'zip'],
            'max_kb' => 5120,
        ],
        'vendor_document' => [
            'kind' => 'direct',
            'folder' => 'support',
            'prefix' => 'file_',
            'date_folder' => false,
            'extensions' => ['jpg', 'jpeg', 'png', 'gif', 'webp', 'pdf', 'doc', 'docx'],
            'max_kb' => 7242,
        ],
        'feedback_image' => [
            'kind' => 'optimized',
            'folder' => 'feedback',
            'date_folder' => true,
            'quality' => 85,
            'extensions' => ['jpg', 'jpeg', 'webp', 'png', 'gif'],
            'variants' => [
                'default' => ['prefix' => 'feedback_', 'method' => 'resize', 'width' => 960, 'height' => null],
            ],
            'default_variant' => 'default',
            'max_kb' => 5120,
        ],
    ],
];
