<?php

return [
    'admin' => [
        'analytics_cache_seconds' => (int) env('ADMIN_ANALYTICS_CACHE_SECONDS', 300),
    ],

    'platform_settings' => [
        'site_name' => env('APP_NAME', 'Selloff'),
        'site_description' => 'Multi-vendor marketplace',
        'primary_color' => '#0075bb',
        'site_logo_url' => '/selloff-logo.png',
        'site_favicon_url' => '/favicon.svg',
        'marketplace_enabled' => true,
        'bidding_enabled' => true,
        'product_reviews_enabled' => true,
        'vendor_feedback_enabled' => true,
        'blog_comments_enabled' => true,
        'multi_vendor_system' => true,
        'site_announcement' => '',
        'about_footer' => 'Selloff is a multi-vendor marketplace for buyers and sellers.',
        'copyright' => '© Selloff. All rights reserved.',
        'facebook_url' => '',
        'twitter_url' => '',
        'instagram_url' => '',
        'maintenance_mode' => false,
        'maintenance_message' => '',
        'image_file_format' => 'WEBP',
        'watermark_text' => '',
        'watermark_font_size' => 28,
        'watermark_product_enabled' => false,
        'watermark_blog_enabled' => false,
        'watermark_thumbnail_enabled' => false,
        'watermark_horizontal_align' => 'right',
        'watermark_vertical_align' => 'bottom',
        'multilingual_system' => false,
        'location_search_header' => true,
        'single_country_mode' => true,
        'single_country_id' => null,
        'index_products_per_row' => 5,
        'product_grid_layout' => 'rows',
        'index_recommended_products_count' => 10,
        'index_latest_products' => true,
        'index_latest_products_count' => 8,
        'index_promoted_products' => true,
        'promoted_products' => true,
        'featured_categories' => true,
        'fea_categories_design' => 'round_boxes',
        'menu_limit' => 8,
        'selected_navigation' => 1,
        'product_img_display_mode' => 'cover',
        'slider_status' => true,
        'slider_type' => 'full_width',
        'slider_effect' => 'fade',
        'index_blog_slider' => true,
        'index_promoted_products_count' => 12,
        'index_trending_products_count' => 12,
        'homepage_site_banner_mid_image' => null,
        'homepage_site_banner_mid_alt' => 'Selloff.ng Banner',
        'show_vendor_contact_information' => true,
        'request_documents_vendors' => true,
        'explanation_documents_vendors' => 'Upload a government-issued ID and a selfie holding your ID with today\'s date and Selloff.ng written on paper.',
        'sort_categories' => 'category_order',
        'sort_parent_categories_by_order' => true,
        'brand_status' => false,
        'is_brand_optional' => true,
        'brand_where_to_display' => 2,
        'timezone' => 'Africa/Lagos',
        'physical_products_enabled' => true,
        'digital_products_enabled' => true,
        'classified_ads_enabled' => true,
        'classified_first_default' => true,
        'license_keys_enabled' => false,
        'guest_checkout_enabled' => true,
        'vendor_verification_system' => false,
        'show_vendor_contact_info_guests' => false,
        'pwa_enabled' => false,
        'rss_enabled' => true,
        'approve_before_publishing' => false,
        'vendor_bulk_product_upload' => false,
        'show_sold_products' => true,
        'comment_approval_system' => true,
        'refund_system' => true,
        'profile_number_of_sales' => true,
        'vendors_change_shop_name' => true,
        'auto_approve_orders' => false,
        'auto_approve_orders_days' => 7,
        'wallet_status' => true,
        'wallet_deposit' => true,
        'pay_with_wallet_balance' => true,
        'wallet_min_deposit' => 100,
        'is_product_image_required' => true,
        'product_image_limit' => 10,
        'max_file_size_image' => 10,
        'max_file_size_video' => 50,
        'max_file_size_audio' => 20,
        'approve_after_editing' => 0,
        'product_link_structure' => 'slug-id',
        'product_comments_enabled' => true,
        'show_customer_email_seller' => true,
        'show_customer_phone_seller' => true,
        'pwa_logo_md_url' => '',
        'pwa_logo_paths' => '',
        'storage' => 'local',
        'aws_key' => '',
        'aws_secret' => '',
        'aws_bucket' => '',
        'aws_region' => '',
        'r2_key' => '',
        'r2_secret' => '',
        'r2_bucket' => '',
        'r2_endpoint_url' => '',
        'r2_public_url' => '',
        'b2_key' => '',
        'b2_secret' => '',
        'b2_bucket' => '',
        'b2_endpoint_url' => '',
        'b2_public_url' => '',
        'ai_writer_api_key' => '',
        'newsletter_status' => true,
        'newsletter_popup_active' => false,
        'newsletter_image_url' => '',
        'application_name' => 'Selloff',
        'site_title' => 'Selloff',
        'homepage_title' => 'Selloff — Marketplace',
        'keywords' => '',
        'contact_address' => '',
        'contact_email' => 'support@selloff.ng',
        'contact_phone' => '',
        'contact_text' => '',
        'tiktok_url' => '',
        'whatsapp_url' => '',
        'youtube_url' => '',
        'linkedin_url' => '',
        'pinterest_url' => '',
        'telegram_url' => '',
        'discord_url' => '',
        'twitch_url' => '',
        'vk_url' => '',
        'facebook_comment_status' => false,
        'facebook_comment' => '',
        'custom_header_codes' => '',
        'custom_footer_codes' => '',
        'gtm_enabled' => true,
        'gtm_container_id' => 'GTM-KH2RZXK',
        'cookies_warning' => false,
        'cookies_warning_text' => '',
        'bulk_upload_documentation' => '',
        'turnstile_status' => false,
        'turnstile_site_key' => '',
        'turnstile_secret_key' => '',
        'maintenance_mode_title' => 'Maintenance',
        'maintenance_mode_description' => '',
        'maintenance_mode_status' => false,
        'marketplace_sku' => true,
        'product_safety_tips' => [
            'Check the item very well and ask questions before you buy it.',
            "Unless you're paying via Selloff Escrow payment on our site, you are advised to not make advance payment before delivery.",
            "If you're picking up an item, ensure you meet in a public place: Never meet with a seller in a secret and lonely place. If you ever have to meet up with a seller, ensure you do so in a public place you are familiar with where you can get help if the worst arises.",
            'Secure your account by using a strong password.',
            'Report suspicious activities immediately.',
        ],
        'marketplace_variations' => true,
        'marketplace_shipping' => true,
        'marketplace_product_location' => true,
        'classified_price' => true,
        'classified_price_required' => false,
        'classified_external_link' => true,
        'classified_product_location' => true,
        'physical_demo_url' => true,
        'physical_video_preview' => true,
        'physical_audio_preview' => true,
        'ai_writer_status' => false,
        'digital_demo_url' => true,
        'digital_video_preview' => true,
        'digital_audio_preview' => true,
        'digital_external_link' => true,
        'digital_allowed_file_extensions' => 'zip,pdf,jpg,png',
        'sort_by_featured_products' => true,
        'pagination_per_page' => 60,
        'commission_rate' => 0,
        'vat_status' => false,
        'cart_location_selection' => true,
        'cash_on_delivery_debt_limit' => 0,
        'allow_all_currencies_for_classified' => false,
        'mail_from_address' => '',
        'mail_from_name' => '',
        'mail_reply_to' => '',
        'mail_service' => 'mailtrap',
        'mailtrap_mode' => 'auto',
        'mailtrap_sandbox_username' => '',
        'mailtrap_sandbox_password' => '',
        'mailtrap_sending_username' => '',
        'mailtrap_sending_password' => '',
        'mail_protocol' => 'smtp',
        'mail_encryption' => 'tls',
        'smtp_host' => '',
        'smtp_port' => '587',
        'smtp_username' => '',
        'smtp_password' => '',
        'brevo_api_key' => '',
        'mailgun_api_key' => '',
        'mailgun_region' => 'us',
        'mailgun_domain' => '',
        'mailgun_sender_email' => '',
        'email_verification' => true,
        'email_option_new_product' => true,
        'email_option_new_order' => true,
        'email_option_order_shipped' => true,
        'email_option_contact_messages' => true,
        'email_option_shop_opening_request' => true,
        'email_option_bidding_system' => true,
        'email_option_support_system' => true,
        'email_option_welcome' => true,
        'email_option_reset_password' => true,
        'email_option_product_moderation' => true,
        'email_option_new_message' => true,
        'email_option_vendor_feedback' => true,
        'email_option_membership_purchase' => true,
        'email_option_membership_expiry' => true,
        'email_option_promotion_applied' => true,
        'email_option_refund' => true,
        'email_option_escrow' => true,
        'mail_options_account' => '',
        'facebook_app_id' => '',
        'facebook_app_secret' => '',
        'google_client_id' => '',
        'google_client_secret' => '',
        'vk_app_id' => '',
        'vk_secure_key' => '',
        'social_login_enabled' => true,
        'site_font_family' => 'Open Sans',
        'dashboard_font_family' => 'Open Sans',
        'custom_fonts' => [],
        'site_logo_email_url' => '',
        'logo_width' => 160,
        'logo_height' => 60,
        'membership_top_boost_duration_days' => 7,
    ],

    'affiliate_program' => [
        'status' => true,
        'type' => 'site_based',
        'commission_rate' => 5,
        'discount_rate' => 1,
        'image_path' => null,
        'image_storage' => '',
        'localized' => [],
    ],

    'referral_program' => [
        'status' => true,
        'points_per_signup' => 10,
        'min_points_to_redeem' => 100,
        'money_per_point' => 10,
        'max_redemptions_per_day' => 3,
        'title' => 'Invite Friends',
        'description' => 'Share your referral code and earn points when friends verify their email. Redeem points to your wallet balance.',
        'how_it_works' => '',
    ],

    'image_url_prefix' => env('SELLOFF_IMAGE_URL_PREFIX', '/storage/'),

    'spa_url' => env('SPA_URL', env('FRONTEND_URL', env('VITE_APP_URL', 'http://localhost:5173'))),

    'mobile_oauth_redirect_scheme' => env('SELLOFF_MOBILE_OAUTH_SCHEME', 'selloff'),

    'escrow_admin_email' => env('SELLOFF_ESCROW_ADMIN_EMAIL', 'escrow@selloff.ng'),

    'escrow_bank' => [
        'account_number' => env('SELLOFF_ESCROW_BANK_ACCOUNT', '1023373630'),
        'bank_name' => env('SELLOFF_ESCROW_BANK_NAME', 'UBA'),
        'account_name' => env('SELLOFF_ESCROW_BANK_HOLDER', 'Selloff NG Limited'),
    ],

    'mail_branding' => [
        'primary' => '#0075bb',
        'escrow_cta' => '#D75A07',
        'success_cta' => '#008D59',
        'confirm_cta' => '#68B503',
        'muted_box' => '#F3F3F3',
        'alert' => '#E10000',
        'emphasis' => '#CE0000',
    ],

    'mail' => [
        'default_service' => env('MAIL_SERVICE', 'mailtrap'),
        'mailtrap_mode' => env('MAILTRAP_MODE', 'auto'),
        'mailtrap_sandbox_username' => env('MAILTRAP_SANDBOX_USERNAME'),
        'mailtrap_sandbox_password' => env('MAILTRAP_SANDBOX_PASSWORD'),
        'mailtrap_sending_username' => env('MAILTRAP_SENDING_USERNAME'),
        'mailtrap_sending_password' => env('MAILTRAP_SENDING_PASSWORD'),
    ],

    'homepage' => [
        'phone_category_slugs' => ['phones-and-tablets'],
        'laptop_category_slugs' => ['electronics/laptops-computers', 'laptops'],
        'phone_section_title' => 'Latest Smartphones & Tablets',
        'laptop_section_title' => 'Latest Laptops and Computers',
        'other_section_title' => 'Latest In Other Categories',
        'site_banners' => [
            'top' => null,
            'mid' => null,
        ],
    ],

    'media_disk' => env('SELLOFF_MEDIA_DISK', 'public'),

    // Legacy MySQL `images.image_*` columns store paths relative to this S3 prefix.
    'legacy_product_image_prefix' => env('SELLOFF_LEGACY_PRODUCT_IMAGE_PREFIX', 'uploads/images'),

    'upload_paths' => [
        'profile' => 'uploads/profile',
        'product' => 'uploads/images',
        'temp' => 'uploads/temp',
    ],

    'rate_limits' => [
        'api_per_minute' => (int) env('SELLOFF_API_RATE_LIMIT', 120),
        'auth_per_minute' => (int) env('SELLOFF_AUTH_RATE_LIMIT', 20),
    ],

    'presence' => [
        // Legacy isUserOnline() used a 2-minute window.
        'online_window_seconds' => (int) env('SELLOFF_PRESENCE_ONLINE_WINDOW', 120),
        'db_write_throttle_seconds' => (int) env('SELLOFF_PRESENCE_DB_THROTTLE', 60),
    ],

    'security' => [
        // When true, Turnstile is off for login/register/forgot/contact regardless of DB settings.
        'turnstile_disabled' => filter_var(env('SELLOFF_TURNSTILE_DISABLED', false), FILTER_VALIDATE_BOOL),
    ],

    'legacy_import' => [
        'default_source' => env('SELLOFF_LEGACY_DUMP', base_path('../docs/data/production-mysql-dump.sql')),
        'memory_limit' => env('SELLOFF_ETL_MEMORY_LIMIT', '1G'),
        'maintenance_window_seconds' => (int) env('SELLOFF_ETL_MAINTENANCE_WINDOW_SECONDS', 14400),
        'verify_image_url_sample_size' => (int) env('SELLOFF_ETL_VERIFY_IMAGE_SAMPLE', 100),
        // Dump tables with no importer — coverage reporting only (never skips importers).
        'coverage_excluded_tables' => [
            'ci_sessions',
            'blog_images',
            'blog_tags',
            'brand_category',
            'cart_items',
            'carts',
            'checkout_items',
            'checkouts',
            'email_queue',
            'fonts',
            'images_file_manager',
            'language_translations',
            'pages_vendor',
            'product_search_indexes',
            'product_settings',
            'settings',
        ],
        // Optional orchestrator safety valve — list LegacyImporter class basenames to skip.
        'exclude_importers' => [],
        // PostgreSQL tables that must exist before live ETL (all selloff:migrate modules).
        'required_schema_tables' => [
            'legacy_import_maps',
            'currencies',
            'languages',
            'countries',
            'roles',
            'users',
            'categories',
            'products',
            'orders',
            'order_items',
        ],
        'verify_tables' => [
            'users' => 'users',
            'categories' => 'categories',
            'products' => 'products',
            'orders' => 'orders',
            'order_items' => 'order_items',
            'location_countries' => 'countries',
            'location_states' => 'states',
            'location_cities' => 'cities',
            'currencies' => 'currencies',
            'languages' => 'languages',
            'shipping_addresses' => 'shipping_addresses',
            'referral_profiles' => 'referral_profiles',
            'brands' => 'brands',
            'wishlist' => 'wishlists',
            'images' => 'product_images',
            'transactions' => 'payment_transactions',
            'refund_requests' => 'refund_requests',
            'refund_requests_messages' => 'refund_messages',
            'roles_permissions' => 'roles',
            'affiliate_links' => 'affiliate_links',
            'affiliate_earnings' => 'affiliate_earnings',
            'wallet_deposits' => 'wallet_deposits',
            'wallet_expenses' => 'wallet_transactions',
            'coupons' => 'coupons',
            'earnings' => 'vendor_earnings',
            'payouts' => 'payout_requests',
            'shipping_zones' => 'shipping_zones',
            'escrow_transactions' => 'escrow_transactions',
            'feedbacks' => 'feedbacks',
            'reviews' => 'product_reviews',
            'followers' => 'followers',
            'comments' => 'comments',
            'chat' => 'conversations',
            'chat_messages' => 'messages',
            'blog_categories' => 'blog_categories',
            'blog_posts' => 'blog_posts',
            'pages' => 'pages',
            'knowledge_base_categories' => 'knowledge_base_categories',
            'knowledge_base' => 'knowledge_base_articles',
            'support_tickets' => 'support_tickets',
            'support_subtickets' => 'support_messages',
            'contacts' => 'contact_messages',
            'tags' => 'tags',
            'product_options' => 'product_options',
            'product_option_values' => 'product_option_values',
            'product_option_variants' => 'product_variants',
            'custom_fields' => 'custom_fields',
            'custom_fields_options' => 'custom_field_options',
            'custom_fields_product' => 'custom_field_product',
            'digital_files' => 'digital_files',
            'product_license_keys' => 'product_license_keys',
            'invoices' => 'invoices',
            'quote_requests' => 'quote_requests',
            'digital_sales' => 'digital_sales',
            'coupons_used' => 'coupon_usages',
            'taxes' => 'tax_rules',
            'bank_transfers' => 'bank_transfer_requests',
            'membership_plans' => 'membership_plans',
            'membership_transactions' => 'membership_transactions',
            'users_membership_plans' => 'user_membership_plans',
            'promoted_transactions' => 'promotion_transactions',
            'user_login_activities' => 'login_activities',
            'abuse_reports' => 'abuse_reports',
            'routes' => 'route_slugs',
            'subscribers' => 'newsletter_subscribers',
            'shipping_delivery_times' => 'delivery_time_options',
            'blog_comments' => 'blog_comments',
            'slider' => 'sliders',
            'homepage_banners' => 'homepage_banners',
            'ad_spaces' => 'ad_spaces',
        ],
    ],

    /**
     * Legacy Modesy role permission slugs (Defaults.php $rolePermissions).
     * Index 20 (storage) is omitted — not used in legacy UI.
     */
    'legacy_role_permissions' => [
        'admin_panel',
        'vendor',
        'theme',
        'slider',
        'homepage_manager',
        'orders',
        'digital_sales',
        'earnings',
        'payouts',
        'refund_requests',
        'products',
        'quote_requests',
        'categories',
        'custom_fields',
        'pages',
        'blog',
        'location',
        'membership',
        'help_center',
        'cache_system',
        'seo_tools',
        'ad_spaces',
        'contact_messages',
        'reviews',
        'comments',
        'abuse_reports',
        'newsletter',
        'preferences',
        'general_settings',
        'product_settings',
        'payment_settings',
        'brands',
        'chat_messages',
        'payments',
        'tags',
        'ai_writer',
    ],

    'catalog' => [
        'custom_filters_load_limit' => 50,
        'custom_filters_collapse_limit' => 3,
    ],

    'location_browse' => [
        'popular_state_names' => [
            'Federal Capital Territory',
            'Lagos',
            'Ogun',
            'Oyo',
            'Rivers',
        ],
        'popular_city_names' => [
            'Oyo' => ['Ibadan', 'Akinyele', 'Egbeda', 'Ido', 'Oluyole'],
        ],
    ],
];
