<?php

return [
    'ci_modules' => [
        'Core',
        'User',
        'Location',
        'Catalog',
        'Vendor',
        'Cart',
        'Order',
        'Payment',
        'Shipping',
        'Escrow',
        'Payout',
        'Promotion',
        'Review',
        'Affiliate',
        'Referral',
        'Notification',
        'Media',
        'Content',
        'Support',
        'Messaging',
        'Admin',
    ],

    'module_order' => [
        'Core',
        'User',
        'Location',
        'Catalog',
        'Vendor',
        'Cart',
        'Order',
        'Payment',
        'Shipping',
        'Escrow',
        'Payout',
        'Promotion',
        'Review',
        'Affiliate',
        'Referral',
        'Notification',
        'Media',
        'Content',
        'Support',
        'Messaging',
        'Admin',
    ],
];
